<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Http\Requests\Auth\LoginRequest;
use App\Providers\RouteServiceProvider;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class AuthenticatedSessionController extends Controller
{
    /**
     * Display the login view.
     */
    public function create(): View
    {
        // Don't regenerate token here - it causes mismatch issues
        // The token is already generated by the middleware
        return view('auth.login');
    }

    /**
     * Handle an incoming authentication request.
     */
    public function store(LoginRequest $request)
    {
        $request->authenticate();

        $request->session()->regenerate();

        // Ensure session is saved before redirect
        $request->session()->save();

        // Log successful login for debugging
        \Log::info('User logged in', [
            'user_id' => Auth::id(),
            'intended_url' => $request->session()->get('url.intended'),
            'redirect_to' => RouteServiceProvider::HOME,
            'is_ajax' => $request->expectsJson(),
        ]);

        // Get redirect URL: intended, or dashboard for admins, my-bookings for customers
        $default = Auth::user()->hasRole('admin') ? RouteServiceProvider::HOME : route('my-bookings');
        $redirectUrl = $request->session()->pull('url.intended', $default);
        
        // Handle AJAX requests
        if ($request->expectsJson()) {
            return response()->json([
                'redirect' => $redirectUrl,
                'message' => 'Login successful',
            ]);
        }
        
        // Force a hard redirect with 302 status
        return redirect($redirectUrl, 302);
    }

    /**
     * Destroy an authenticated session.
     */
    public function destroy(Request $request): RedirectResponse
    {
        Auth::guard('web')->logout();

        $request->session()->invalidate();

        $request->session()->regenerateToken();

        return redirect('/');
    }
}
